### ISSUE TITLE
Flag?

### ISSUE THREAD

**Issue by umar-mq** [overcrash66/Audio-File-Translator---S2ST#1]
Why do you have a large Palestinian flag in the center? (Just out of curiosity.)

**Comment by overcrash66** [comment]
I support Palestine and i am thinking about Palestinians a lot these days.. 

Please feel free to change the flag to something else if you would like to use this tool but speaking for myself it will always stay as a Palestine flag .

**Comment by umar-mq** [comment]
> I support Palestine and i am thinking about Palestinians a lot these days..

That is no problem as I am also supporting Palestine. I was just wondering as it is a surprising thing to put on a app.
